### ISSUE TITLE
rename repo to Plotly-Mathematica-API

### ISSUE THREAD

**Issue by chriddyp** [Nevensky/plotly-mathematica#8]
Just a suggestion - renaming the repo to have the keywords separated by hyphens will likely help it appear when people are searching for this on google! Here is a reference: https://www.mattcutts.com/blog/dashes-vs-underscores/. Github handles the redirects, so all of the links to https://github.com/Nevensky/plotlymathematica should redirect to the new name.

**Comment by Nevensky** [comment]
Thanks for the suggestion, it's been done.

—
Lijepi pozdrav,
Neven Golenić
